/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/BloodView/aside.vue')['default']
    BloodView: typeof import('./src/components/BloodView/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/BloodView/footer.vue')['default']
    Header: typeof import('./src/components/BloodView/header.vue')['default']
    JsonEdit: typeof import('./src/components/BloodView/components/jsonEdit.vue')['default']
    Main: typeof import('./src/components/BloodView/main.vue')['default']
    Toolbar: typeof import('./src/components/BloodView/components/toolbar.vue')['default']
    Topbar: typeof import('./src/components/BloodView/components/topbar.vue')['default']
  }
}
